function comp() {
    document.getElementById("mymain").innerHTML='<p><div id="math102" style="font-size: large;color: rebeccapurple;font-weight: bold;">MATH 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">MATH 104</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">COMP 106</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">INCO 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">COMP 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">COMP 104</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">ENGL 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br></p>'
    document.getElementById("bla").innerHTML=""
}
function stat() {
    document.getElementById("mymain").innerHTML='<p><div id="math102" style="font-size: large;color: rebeccapurple;font-weight: bold;">MATH 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">MATH 104</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">STAT 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">INCO 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">COMP 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">COMP 104</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br><div id="math104" style="font-size: large;color: rebeccapurple;font-weight: bold;">ENGL 102</div>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br>Soon<br></p>'
    document.getElementById("bla").innerHTML=""
}
function math() {
    document.getElementById("mymain").innerHTML='<P style="color: black;font-size: x-large;font-weight: bold;text-align: center;">No Matrial Yet</P>'
    document.getElementById("bla").innerHTML=""
}
